# Generated by Django 6.0.6 on 2026-06-17 11:29

import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDecibel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_decibel', models.IntegerField()),
                ('min_decibel', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Decibel',
            },
        ),
        migrations.CreateModel(
            name='VideoAspectRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aspect Ratios',
            },
        ),
        migrations.CreateModel(
            name='VideoDurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durations', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Duraions',
            },
        ),
        migrations.CreateModel(
            name='VideoFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Formats',
            },
        ),
        migrations.CreateModel(
            name='VideoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=150)),
                ('video_type', models.CharField(max_length=25)),
                ('video_width', models.IntegerField(default=0)),
                ('video_height', models.IntegerField(default=0)),
                ('resolution', models.CharField(max_length=150)),
                ('aspect_ratio', models.CharField(max_length=150)),
                ('video_fps', models.CharField(max_length=20)),
                ('video_bit_rate', models.CharField(max_length=150)),
                ('audio_bit_rate', models.CharField(max_length=150)),
                ('audio_sample_rate', models.CharField(max_length=150)),
                ('max_audio_decibel', models.CharField(max_length=150)),
                ('video_codec', models.CharField(max_length=150)),
                ('audio_codec', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('name_width', models.IntegerField(default=0)),
                ('name_height', models.IntegerField(default=0)),
                ('upload_instance', models.IntegerField(default=0)),
                ('sl_no', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('video_src', models.FileField(blank=True, null=True, upload_to=video.models.video_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Table',
            },
        ),
        migrations.CreateModel(
            name='VideoTableMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=150)),
                ('video_type', models.CharField(max_length=25)),
                ('video_width', models.IntegerField(default=0)),
                ('video_height', models.IntegerField(default=0)),
                ('resolution', models.CharField(max_length=150)),
                ('aspect_ratio', models.CharField(max_length=150)),
                ('video_fps', models.CharField(max_length=20)),
                ('video_bit_rate', models.CharField(max_length=150)),
                ('audio_bit_rate', models.CharField(max_length=150)),
                ('audio_sample_rate', models.CharField(max_length=150)),
                ('max_audio_decibel', models.CharField(max_length=150)),
                ('video_codec', models.CharField(max_length=150)),
                ('audio_codec', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('name_width', models.IntegerField(default=0)),
                ('name_height', models.IntegerField(default=0)),
                ('upload_instance', models.IntegerField(default=0)),
                ('sl_no', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Video Table Metadata',
            },
        ),
    ]
