# Generated by Django 6.0.6 on 2026-06-17 11:29

import django.db.models.deletion
import image.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('size_kb', models.IntegerField(default=0)),
                ('img_type', models.CharField(max_length=25)),
                ('img_width', models.IntegerField(default=0)),
                ('img_height', models.IntegerField(default=0)),
                ('name_width', models.IntegerField(default=0)),
                ('name_height', models.IntegerField(default=0)),
                ('upload_instance', models.IntegerField(default=0)),
                ('sl_no', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('img_src', models.FileField(blank=True, null=True, upload_to=image.models.image_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image Table',
            },
        ),
        migrations.CreateModel(
            name='ImageTableMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('size_kb', models.IntegerField(default=0)),
                ('img_type', models.CharField(max_length=25)),
                ('img_width', models.IntegerField(default=0)),
                ('img_height', models.IntegerField(default=0)),
                ('name_width', models.IntegerField(default=0)),
                ('name_height', models.IntegerField(default=0)),
                ('upload_instance', models.IntegerField(default=0)),
                ('sl_no', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image Table Meta Data',
            },
        ),
    ]
